name: Build

on: [ push, pull_request ]

jobs:
  build-all:
    strategy:
      matrix:
        distro: [ 'ubuntu-18.04', 'ubuntu-20.04' ]
        cc: [ 'gcc', 'clang' ]
    name: Build
    runs-on: ${{ matrix.distro }}
    steps:

      - name: Update repositories
        run: sudo apt-get update

      - name: Install meson and ninja
        run: sudo apt-get install meson ninja-build

      - name: Install vala
        run: sudo apt-get install valac

      - name: Install gcc
        run: sudo apt-get install gcc

      - name: Install clang
        run: sudo apt-get install clang

      - name: Install dependencies
        run: sudo apt-get install gtk+3.0 libgtk-3-dev

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare compilation with Meson
        run: meson setup build
        env:
          CC: ${{ matrix.cc }}

      - name: Compile with Ninja
        run: ninja -C build
        env:
          CC: ${{ matrix.cc }}
